apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ranking
  labels:
    app: ecommerce-ranking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ranking
  template:
    metadata:
      labels:
        app: ecommerce-ranking
    spec:
      containers:
        - name: ecommerce-ranking
          image: 763835215122.dkr.ecr.ap-northeast-1.amazonaws.com/eks-ecommerce:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"