apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ranking
spec:
  selector:
    app: ecommerce-ranking
  ports:
    - protocol: TCP
      port: 80 # 對外訪問的端口
      targetPort: 8080 # 映射到 Pod 容器的端口
  type: LoadBalancer
