apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::763835215122:role/GitHubActionsRole
      username: github-actions
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::763835215122:role/GitHubActionsRole\n  username: github-actions\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2026-03-08T09:22:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "56987"
  uid: bd3a3c56-c029-40f1-b21e-4de5a50006d8